% This is all global data shared between the matlab functions for reading
% ERD databases

% Header
clear  HEADER VALIDFILEVERSION FILEVERSION NBYTESFORNODEID ISSET_VELOCITY ISSET_FLOW ISSET_DEMAND ISSET_PRESSURE ISSET_DEMANDPROFILE;
% Potential causes of screwing up the database reads
clear  FILEPOS MAXFNAME;
% Network size info
clear  HYDSIMCOUNT QUALSIMCOUNT NNODES NLINKS NTANKS NJUNCTIONS NSTEPS NSPECIES QUALCODE NSTOREDSPECIES SIMDURATION REPORTSTART REPORTSTEP FLTMAX STEPSIZE;
% Control link info
clear  NUMCONTROLLINKS CONTROLLINKS;
% Patterns
clear  PATTERN PATTERNLENGTH;
% Network objects
clear  TANKINDEX NODEID LINKID SPECIEIDX SPECIETYPE SPECIEID XNODE YNODE FROMNODE TONODE LENGTH NV VERTX VERTY;
% Database file names
clear  HYDFILENAME QUALFILENAME;
% Hydraulic simulation data
clear  D Q V P HYDFILEIDX HYDLENGTH HYDOFFSET;
% Quality simulatoin data
clear  C QUALFILEIDX HYDSIMIDX QUALLENGTH QUALOFFSET QUALINPFNAME QUALMSXFNAME;
% Matlab file IDs
clear  ERDprologueFID ERDindexFID ERDhydFID ERDqualFID;
