# Copyright (2013) Sandia Corporation. Under the terms of Contract
# DE-AC04-94AL85000 with Sandia Corporation, the U.S. Government 
# retains certain rights in this software.
#
# This software is released under the FreeBSD license as described 
# in License.txt

import os
import sys
import datetime
import _gui
import json # Python 2.6 or later

def printLine(bPrint, kml_file, sText):
	if kml_file <> None: kml_file.write(sText)
	return sText

def printNode(bPrint, kml_file, Type, id, lon, lat, status="", visibility=1, band="", objective=None):
	loc = "Lat, Lon = " + str(lat) + ", " + str(lon)
	if Type == "Inversion":
		desc = "Possible Source Location\n" + loc
		desc += "\nProbability = " + str(objective)
	elif Type == "GrabSample":
		desc = "Grab Sample Location\n" + loc
		if len(status) == 0:
			desc += "\nSample status = Waiting..."
		else:
			desc += "\nSample status = " + status
	elif Type == "Sensor":
		desc = "Continuous Sensor Location\n" + loc
	sText = ""
	sText += printLine(bPrint, kml_file, '<Placemark>')
	sText += printLine(bPrint, kml_file, '<name>' + id + '</name>')
	if visibility == 0: sText += printLine(bPrint, kml_file, '<visibility>' + str(visibility) + '</visibility>')
	sText += printLine(bPrint, kml_file, '<description>' + desc  + '</description>')
	sText += printLine(bPrint, kml_file, '<styleUrl>#' + Type + status + band + '</styleUrl>')
	sText += printLine(bPrint, kml_file, '<Point>')
	sText += printLine(bPrint, kml_file, '<coordinates>' + str(lon) + ',' + str(lat) + ',0</coordinates>')
	sText += printLine(bPrint, kml_file, '</Point>')
	sText += printLine(bPrint, kml_file, '</Placemark>')
	return sText

def printLink(bPrint, kml_file, Type, id, lon1, lat1, lon2, lat2, lon=None, lat=None):
	sText = ""
	if Type == "Pump" or Type == "Valve":
		sText += printLine(bPrint, kml_file, '<Placemark>')
		sText += printLine(bPrint, kml_file, '<name>' + id + '</name>')
		sText += printLine(bPrint, kml_file, '<styleUrl>#' + Type + 'Label</styleUrl>')
		sText += printLine(bPrint, kml_file, '<Point>')
		sText += printLine(bPrint, kml_file, '<coordinates>' + str(lon) + ',' + str(lat) + ',0</coordinates>')
		sText += printLine(bPrint, kml_file, '</Point>')
		sText += printLine(bPrint, kml_file, '</Placemark>')
	sText += printLine(bPrint, kml_file, '<Placemark>')
	sText += printLine(bPrint, kml_file, '<name>' + id + '</name>')
	sText += printLine(bPrint, kml_file, '<styleUrl>#' + Type + '</styleUrl>')
	sText += printLine(bPrint, kml_file, '<LineString>')
	sText += printLine(bPrint, kml_file, '<coordinates>' + str(lon1) + ',' + str(lat1) + ',0 ' + str(lon2) + ',' + str(lat2) + ',0</coordinates>')
	sText += printLine(bPrint, kml_file, '</LineString>')
	sText += printLine(bPrint, kml_file, '</Placemark>')
	return sText

def printStylesInversion(bPrint, kml_file):
	sText = ""
	for i in range(0, 10):
		sText += printLine(bPrint, kml_file, '<StyleMap id="Inversion' + str(i) + '">')
		sText += printLine(bPrint, kml_file, '<Pair>')
		sText += printLine(bPrint, kml_file, '<key>')
		sText += printLine(bPrint, kml_file, 'normal')
		sText += printLine(bPrint, kml_file, '</key>')
		sText += printLine(bPrint, kml_file, '<styleUrl>')
		sText += printLine(bPrint, kml_file, '#Inversion' + str(i) + 'Normal')
		sText += printLine(bPrint, kml_file, '</styleUrl>')
		sText += printLine(bPrint, kml_file, '</Pair>')
		sText += printLine(bPrint, kml_file, '<Pair>')
		sText += printLine(bPrint, kml_file, '<key>')
		sText += printLine(bPrint, kml_file, 'highlight')
		sText += printLine(bPrint, kml_file, '</key>')
		sText += printLine(bPrint, kml_file, '<styleUrl>')
		sText += printLine(bPrint, kml_file, '#Inversion' + str(i) + 'Highlight')
		sText += printLine(bPrint, kml_file, '</styleUrl>')
		sText += printLine(bPrint, kml_file, '</Pair>')
		sText += printLine(bPrint, kml_file, '</StyleMap>')
		#
		sText += printLine(bPrint, kml_file, '<Style id="Inversion' + str(i) + 'Normal">')
		sText += printLine(bPrint, kml_file, '<BalloonStyle>')
		#sText += printLine(bPrint, kml_file, '<text>')
		#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
		#sText += printLine(bPrint, kml_file, '</text>')
		sText += printLine(bPrint, kml_file, '<bgColor>')
		sText += printLine(bPrint, kml_file, 'bb0000bb')
		sText += printLine(bPrint, kml_file, '</bgColor>')
		sText += printLine(bPrint, kml_file, '<textColor>')
		sText += printLine(bPrint, kml_file, 'ff000000')
		sText += printLine(bPrint, kml_file, '</textColor>')
		sText += printLine(bPrint, kml_file, '</BalloonStyle>')
		sText += printLine(bPrint, kml_file, '<IconStyle>')
		sText += printLine(bPrint, kml_file, '<Icon>')
		sText += printLine(bPrint, kml_file, '<href>')
		#sText += printLine(bPrint, kml_file, 'inversion' + str(i) + '.png')
		sText += printLine(bPrint, kml_file, 'inversion.png')
		sText += printLine(bPrint, kml_file, '</href>')
		sText += printLine(bPrint, kml_file, '</Icon>')
		sText += printLine(bPrint, kml_file, '<scale>')
		sText += printLine(bPrint, kml_file, str(0.045 * (i + 1)))
		sText += printLine(bPrint, kml_file, '</scale>')
		sText += printLine(bPrint, kml_file, '</IconStyle>')
		sText += printLine(bPrint, kml_file, '<LabelStyle>')
		sText += printLine(bPrint, kml_file, '<scale>')
		sText += printLine(bPrint, kml_file, '0.0')
		sText += printLine(bPrint, kml_file, '</scale>')
		sText += printLine(bPrint, kml_file, '</LabelStyle>')
		sText += printLine(bPrint, kml_file, '</Style>')
		#
		sText += printLine(bPrint, kml_file, '<Style id="Inversion' + str(i) + 'Highlight">')
		sText += printLine(bPrint, kml_file, '<BalloonStyle>')
		#sText += printLine(bPrint, kml_file, '<text>')
		#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
		#sText += printLine(bPrint, kml_file, '</text>')
		sText += printLine(bPrint, kml_file, '<bgColor>')
		sText += printLine(bPrint, kml_file, 'bb0000bb')
		sText += printLine(bPrint, kml_file, '</bgColor>')
		sText += printLine(bPrint, kml_file, '<textColor>')
		sText += printLine(bPrint, kml_file, 'ff000000')
		sText += printLine(bPrint, kml_file, '</textColor>')
		sText += printLine(bPrint, kml_file, '</BalloonStyle>')
		sText += printLine(bPrint, kml_file, '<IconStyle>')
		sText += printLine(bPrint, kml_file, '<Icon>')
		sText += printLine(bPrint, kml_file, '<href>')
		#sText += printLine(bPrint, kml_file, 'inversion' + str(i) + '.png')
		sText += printLine(bPrint, kml_file, 'inversion.png')
		sText += printLine(bPrint, kml_file, '</href>')
		sText += printLine(bPrint, kml_file, '</Icon>')
		sText += printLine(bPrint, kml_file, '<scale>')
		sText += printLine(bPrint, kml_file, str(0.045 * (i + 1)))
		sText += printLine(bPrint, kml_file, '</scale>')
		sText += printLine(bPrint, kml_file, '</IconStyle>')
		sText += printLine(bPrint, kml_file, '<LabelStyle>')
		sText += printLine(bPrint, kml_file, '<scale>')
		sText += printLine(bPrint, kml_file, '1.0')
		sText += printLine(bPrint, kml_file, '</scale>')
		sText += printLine(bPrint, kml_file, '</LabelStyle>')
		sText += printLine(bPrint, kml_file, '</Style>')
	return sText

def printStyles(bPrint, kml_file):
	sText = ""
	sText += printStylesInversion(bPrint, kml_file)

	sText += printLine(bPrint, kml_file, '<StyleMap id="Sensor">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#SensorNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#SensorHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="GrabSample">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#GrabSampleNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#GrabSampleHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="GrabSampleBackground">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#GrabSampleBackgroundNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#GrabSampleBackgroundHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="GrabSampleAbnormal">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#GrabSampleAbnormalNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#GrabSampleAbnormalHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="Junction">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#JunctionNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#JunctionHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="Reservoir">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#ReservoirNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#ReservoirHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="Tank">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#TankNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#TankHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<Style id="Downstream">')
	sText += printLine(bPrint, kml_file, '<LineStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, '9900eeee')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<width>')
	sText += printLine(bPrint, kml_file, '6')
	sText += printLine(bPrint, kml_file, '</width>')
	sText += printLine(bPrint, kml_file, '</LineStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="DownstreamAbnormal">')
	sText += printLine(bPrint, kml_file, '<LineStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, '990000ee')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<width>')
	sText += printLine(bPrint, kml_file, '6')
	sText += printLine(bPrint, kml_file, '</width>')
	sText += printLine(bPrint, kml_file, '</LineStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="DownstreamBackground">')
	sText += printLine(bPrint, kml_file, '<LineStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, '9900ee00')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<width>')
	sText += printLine(bPrint, kml_file, '6')
	sText += printLine(bPrint, kml_file, '</width>')
	sText += printLine(bPrint, kml_file, '</LineStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="Valve">')
	sText += printLine(bPrint, kml_file, '<LineStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, 'FFC8C800')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<width>')
	sText += printLine(bPrint, kml_file, '8')
	sText += printLine(bPrint, kml_file, '</width>')
	sText += printLine(bPrint, kml_file, '</LineStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="ValveLabel">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#ValveLabelNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#ValveLabelHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<Style id="Pump">')
	sText += printLine(bPrint, kml_file, '<LineStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, 'FF00C8C8')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<width>')
	sText += printLine(bPrint, kml_file, '8')
	sText += printLine(bPrint, kml_file, '</width>')
	sText += printLine(bPrint, kml_file, '</LineStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<StyleMap id="PumpLabel">')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'normal')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#PumpLabelNormal')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '<Pair>')
	sText += printLine(bPrint, kml_file, '<key>')
	sText += printLine(bPrint, kml_file, 'highlight')
	sText += printLine(bPrint, kml_file, '</key>')
	sText += printLine(bPrint, kml_file, '<styleUrl>')
	sText += printLine(bPrint, kml_file, '#PumpLabelHighlight')
	sText += printLine(bPrint, kml_file, '</styleUrl>')
	sText += printLine(bPrint, kml_file, '</Pair>')
	sText += printLine(bPrint, kml_file, '</StyleMap>')

	sText += printLine(bPrint, kml_file, '<Style id="Pipe">')
	sText += printLine(bPrint, kml_file, '<LineStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, '80000000')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<width>')
	sText += printLine(bPrint, kml_file, '4')
	sText += printLine(bPrint, kml_file, '</width>')
	sText += printLine(bPrint, kml_file, '</LineStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="PipeLabel">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'pipe.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="PumpLabelNormal">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'pump.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="PumpLabelHighlight">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'pump.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="ValveLabelNormal">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'valve.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="ValveLabelHighlight">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'valve.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="TankNormal">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'tank.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="TankHighlight">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'tank.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="ReservoirNormal">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'reservoir.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="ReservoirHighlight">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'reservoir.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="JunctionNormal">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'junction.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="JunctionHighlight">')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'junction.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="GrabSampleAbnormalNormal">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bb0000bb')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'grabsample_abnormal.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.5')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="GrabSampleAbnormalHighlight">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bb0000bb')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'grabsample_abnormal.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.5')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	#sText += printLine(bPrint, kml_file, 'ff8989ff')
	sText += printLine(bPrint, kml_file, 'ff9999ff')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.8')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="GrabSampleBackgroundNormal">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bb00bb00')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'grabsample_background.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.5')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="GrabSampleBackgroundHighlight">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bb00bb00')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'grabsample_background.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.5')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.8')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, 'ff00ff00')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="GrabSampleNormal">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bb00bbbb')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'grabsample_.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.8')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.8')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, 'ff00d1e1')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="GrabSampleHighlight">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bb00bbbb')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'grabsample_.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.8')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	sText += printLine(bPrint, kml_file, 'ff00d1e1')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.4')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="SensorNormal">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bbbb0000')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'sensor.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '0.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '<color>')
	#sText += printLine(bPrint, kml_file, 'ffff0000')
	#sText += printLine(bPrint, kml_file, 'fff6a309')
	sText += printLine(bPrint, kml_file, 'fff48985')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')

	sText += printLine(bPrint, kml_file, '<Style id="SensorHighlight">')
	sText += printLine(bPrint, kml_file, '<BalloonStyle>')
	#sText += printLine(bPrint, kml_file, '<text>')
	#sText += printLine(bPrint, kml_file, '$[name]\n$[description]')
	#sText += printLine(bPrint, kml_file, '</text>')
	sText += printLine(bPrint, kml_file, '<bgColor>')
	sText += printLine(bPrint, kml_file, 'bbbb0000')
	sText += printLine(bPrint, kml_file, '</bgColor>')
	sText += printLine(bPrint, kml_file, '<textColor>')
	sText += printLine(bPrint, kml_file, 'ff000000')
	sText += printLine(bPrint, kml_file, '</textColor>')
	sText += printLine(bPrint, kml_file, '</BalloonStyle>')
	sText += printLine(bPrint, kml_file, '<IconStyle>')
	sText += printLine(bPrint, kml_file, '<Icon>')
	sText += printLine(bPrint, kml_file, '<href>')
	sText += printLine(bPrint, kml_file, 'sensor.png')
	sText += printLine(bPrint, kml_file, '</href>')
	sText += printLine(bPrint, kml_file, '</Icon>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.0')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</IconStyle>')
	sText += printLine(bPrint, kml_file, '<LabelStyle>')
	sText += printLine(bPrint, kml_file, '<color>')
	#sText += printLine(bPrint, kml_file, 'ffff0000')
	#sText += printLine(bPrint, kml_file, 'fff6a309')
	sText += printLine(bPrint, kml_file, 'fff48985')
	sText += printLine(bPrint, kml_file, '</color>')
	sText += printLine(bPrint, kml_file, '<scale>')
	sText += printLine(bPrint, kml_file, '1.4')
	sText += printLine(bPrint, kml_file, '</scale>')
	sText += printLine(bPrint, kml_file, '</LabelStyle>')
	sText += printLine(bPrint, kml_file, '</Style>')
	return sText

def printFile(bPrint, kml_file, data, sFile, zFactor, encryption, bFirstFile=False, bLastFile=False):
	sText = ""
	#
	# Printing kml header
	#
	if bFirstFile:
		sText += printLine(bPrint, kml_file, '<?xml version="1.0" encoding="UTF-8"?>')
		sText += printLine(bPrint, kml_file, '<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">')
		sText += printLine(bPrint, kml_file, '<Document>')
		if sFile == "Inversion" or sFile == "GrabSample":
			sText += printLine(bPrint, kml_file, '<name>' + sFile + '</name>')
		else:
			sText += printLine(bPrint, kml_file, '<name>All</name>')
		#sText += printLine(bPrint, kml_file, '<description></description>')
		#sText += printLine(bPrint, kml_file, '<description><![CDATA[testing]]></description>')
		#
		sText += printStyles(bPrint, kml_file)
	#
	a  = zFactor["a"]
	bx = zFactor["bx"] - encryption * a
	by = zFactor["by"] - encryption * a
	#
	# Printing Nodes and Links and Inversion and GrabSample
	#
	nLen = len(data)
	if sFile == "Inversion":
		for i in range(nLen, 0, -1):
			item = data[i-1]
			x = (float(item["x"]) + bx) / a
			y = (float(item["y"]) + by) / a
			objective = item["Objective"]
			size = item["Size"]
			sBand = "9"
			if size < 0.9: sBand = "8"
			if size < 0.8: sBand = "7"
			if size < 0.7: sBand = "6"
			if size < 0.6: sBand = "5"
			if size < 0.5: sBand = "4"
			if size < 0.4: sBand = "3"
			if size < 0.3: sBand = "2"
			if size < 0.2: sBand = "1"
			if size < 0.1: sBand = "0"
			sText += printNode(bPrint, kml_file, "Inversion", item["Name"], x, y, band=sBand, objective=objective)
	#
	if sFile == "GrabSample":
		for i in range(nLen, 0, -1):
			item = data[i-1]
			x = (float(item["x"]) + bx) / a
			y = (float(item["y"]) + by) / a
			status = item["Status"]
			sText += printNode(bPrint, kml_file, "GrabSample", item["Name"], x, y, status=status)
			i = 0
			streams = item["downstream"]
			if streams == None: streams = []
			for stream in streams:
				i = i + 1
				x1 = (stream["x1"] + bx) / a
				y1 = (stream["y1"] + by) / a
				x2 = (stream["x2"] + bx) / a
				y2 = (stream["y2"] + by) / a
				sText += printLink(bPrint, kml_file, "Downstream" + status, item["Name"], x1, y1, x2, y2)
	#
	if sFile == "Sensor":
		for item in data:
			x = (float(item["x"]) + bx) / a
			y = (float(item["y"]) + by) / a
			sText += printNode(bPrint, kml_file, "Sensor", item["Name"], x, y, visibility=0)
	#
	if sFile == "Pipes" or sFile == "Valves" or sFile == "Pumps":
		for item in data[sFile]:
			x1 = (float(item["x1"]) + bx) / a
			y1 = (float(item["y1"]) + by) / a
			x2 = (float(item["x2"]) + bx) / a
			y2 = (float(item["y2"]) + by) / a
			x = (x1 + x2) / 2
			y = (y1 + y2) / 2
			sText += printLink(bPrint, kml_file, item["Type"], item["ID"], x1, y1, x2, y2, x, y)
	#
	if sFile == "Junctions" or sFile == "Tanks" or sFile == "Reservoirs":
		for item in data[sFile]:
			x = (float(item["x"]) + bx) / a
			y = (float(item["y"]) + by) / a
			sText += printNode(bPrint, kml_file, item["Type"], item["id"], x, y)
	#
	# Printing kml footer
	#
	if bLastFile:
		sText += printLine(bPrint, kml_file, '</Document>')
		sText += printLine(bPrint, kml_file, '</kml>')
	#
	return sText

def printInversionFile(kml_file, results, sensors, data):
	bPrint = (kml_file <> None)
	sText = ""
	sText += printFile(bPrint, kml_file, results, "Inversion" , data["zFactor"], data["encryption"], bFirstFile=True)
	sText += printFile(bPrint, kml_file, sensors, "Sensor"    , data["zFactor"], data["encryption"])
	sText += printFile(bPrint, kml_file, data   , "Pipes"     , data["zFactor"], data["encryption"], bLastFile=True)
	return sText

def printGrabFile(kml_file, results, sensors, data):
	bPrint = (kml_file <> None)
	sText = ""
	sText += printFile(bPrint, kml_file, results, "GrabSample", data["zFactor"], data["encryption"], bFirstFile=True)
	sText += printFile(bPrint, kml_file, sensors, "Sensor"    , data["zFactor"], data["encryption"])
	sText += printFile(bPrint, kml_file, data   , "Pipes"     , data["zFactor"], data["encryption"], bLastFile=True)
	return sText

def main():
	# Loading json 
	jsonFile = "inp_23.4_30.4.inp.GPM.24.json"
	f = open(jsonFile)
	sText = f.read()
	data = json.loads(sText);
	#
	kml_file = None
	kml_file = open("kml_all.kml","w")
	printFile(True, kml_file, data, "Tanks", bFirstFile=True)
	printFile(True, kml_file, data, "Reservoirs")
	printFile(True, kml_file, data, "Valves")
	printFile(True, kml_file, data, "Pumps")
	printFile(True, kml_file, data, "Junctions")
	printFile(True, kml_file, data, "Pipes", bLastFile=True)
	kml_file.close()

if __name__ == "__main__":
	main()



