# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flushingUi.ui'
#
# Created: Wed Feb 16 16:06:55 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(839, 680)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tempus Sans ITC"))
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_8.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_8)
        self.moduleTabs = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.moduleTabs.setFont(font)
        self.moduleTabs.setTabPosition(QtGui.QTabWidget.West)
        self.moduleTabs.setTabShape(QtGui.QTabWidget.Triangular)
        self.moduleTabs.setObjectName(_fromUtf8("moduleTabs"))
        self.flushingTab = QtGui.QWidget()
        self.flushingTab.setObjectName(_fromUtf8("flushingTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.flushingTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lbl_displayProjectDirectory = QtGui.QLabel(self.flushingTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_displayProjectDirectory.sizePolicy().hasHeightForWidth())
        self.lbl_displayProjectDirectory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.lbl_displayProjectDirectory.setFont(font)
        self.lbl_displayProjectDirectory.setObjectName(_fromUtf8("lbl_displayProjectDirectory"))
        self.gridLayout_7.addWidget(self.lbl_displayProjectDirectory, 0, 0, 1, 1)
        self.displayProjectDirectory = QtGui.QLabel(self.flushingTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayProjectDirectory.sizePolicy().hasHeightForWidth())
        self.displayProjectDirectory.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.displayProjectDirectory.setFont(font)
        self.displayProjectDirectory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.displayProjectDirectory.setObjectName(_fromUtf8("displayProjectDirectory"))
        self.gridLayout_7.addWidget(self.displayProjectDirectory, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.flushingTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 0, 1, 1, 1)
        self.displayProjectName = QtGui.QLabel(self.flushingTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayProjectName.sizePolicy().hasHeightForWidth())
        self.displayProjectName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.displayProjectName.setFont(font)
        self.displayProjectName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayProjectName.setObjectName(_fromUtf8("displayProjectName"))
        self.gridLayout_7.addWidget(self.displayProjectName, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.configTabWidget = QtGui.QTabWidget(self.flushingTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configTabWidget.sizePolicy().hasHeightForWidth())
        self.configTabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.configTabWidget.setFont(font)
        self.configTabWidget.setToolTip(_fromUtf8(""))
        self.configTabWidget.setStatusTip(_fromUtf8(""))
        self.configTabWidget.setObjectName(_fromUtf8("configTabWidget"))
        self.tabOptions = QtGui.QWidget()
        self.tabOptions.setObjectName(_fromUtf8("tabOptions"))
        self.gridLayout = QtGui.QGridLayout(self.tabOptions)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupSimulationOptions = QtGui.QGroupBox(self.tabOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupSimulationOptions.sizePolicy().hasHeightForWidth())
        self.groupSimulationOptions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupSimulationOptions.setFont(font)
        self.groupSimulationOptions.setObjectName(_fromUtf8("groupSimulationOptions"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupSimulationOptions)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.toolButtonFindInp = QtGui.QToolButton(self.groupSimulationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonFindInp.sizePolicy().hasHeightForWidth())
        self.toolButtonFindInp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        font.setItalic(True)
        self.toolButtonFindInp.setFont(font)
        self.toolButtonFindInp.setObjectName(_fromUtf8("toolButtonFindInp"))
        self.gridLayout_4.addWidget(self.toolButtonFindInp, 0, 1, 1, 1)
        self.displayInpFile = QtGui.QLabel(self.groupSimulationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayInpFile.sizePolicy().hasHeightForWidth())
        self.displayInpFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.displayInpFile.setFont(font)
        self.displayInpFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayInpFile.setText(_fromUtf8(""))
        self.displayInpFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayInpFile.setWordWrap(False)
        self.displayInpFile.setObjectName(_fromUtf8("displayInpFile"))
        self.gridLayout_4.addWidget(self.displayInpFile, 0, 2, 1, 1)
        self.toolButtonFindTsg = QtGui.QToolButton(self.groupSimulationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonFindTsg.sizePolicy().hasHeightForWidth())
        self.toolButtonFindTsg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        font.setItalic(True)
        self.toolButtonFindTsg.setFont(font)
        self.toolButtonFindTsg.setObjectName(_fromUtf8("toolButtonFindTsg"))
        self.gridLayout_4.addWidget(self.toolButtonFindTsg, 1, 1, 1, 1)
        self.displayTsgFile = QtGui.QLabel(self.groupSimulationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayTsgFile.sizePolicy().hasHeightForWidth())
        self.displayTsgFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.displayTsgFile.setFont(font)
        self.displayTsgFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayTsgFile.setText(_fromUtf8(""))
        self.displayTsgFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayTsgFile.setWordWrap(False)
        self.displayTsgFile.setObjectName(_fromUtf8("displayTsgFile"))
        self.gridLayout_4.addWidget(self.displayTsgFile, 1, 2, 1, 1)
        self.chooseImpactMetric = QtGui.QComboBox(self.groupSimulationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseImpactMetric.sizePolicy().hasHeightForWidth())
        self.chooseImpactMetric.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.chooseImpactMetric.setFont(font)
        self.chooseImpactMetric.setObjectName(_fromUtf8("chooseImpactMetric"))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.chooseImpactMetric.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.chooseImpactMetric, 2, 1, 1, 1)
        self.displayImpactMetric = QtGui.QLabel(self.groupSimulationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayImpactMetric.sizePolicy().hasHeightForWidth())
        self.displayImpactMetric.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.displayImpactMetric.setFont(font)
        self.displayImpactMetric.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayImpactMetric.setAlignment(QtCore.Qt.AlignCenter)
        self.displayImpactMetric.setWordWrap(False)
        self.displayImpactMetric.setObjectName(_fromUtf8("displayImpactMetric"))
        self.gridLayout_4.addWidget(self.displayImpactMetric, 2, 2, 1, 1)
        self.toolButtonFindTai = QtGui.QToolButton(self.groupSimulationOptions)
        self.toolButtonFindTai.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButtonFindTai.sizePolicy().hasHeightForWidth())
        self.toolButtonFindTai.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        font.setItalic(True)
        self.toolButtonFindTai.setFont(font)
        self.toolButtonFindTai.setObjectName(_fromUtf8("toolButtonFindTai"))
        self.gridLayout_4.addWidget(self.toolButtonFindTai, 3, 1, 1, 1)
        self.displayTaiFile = QtGui.QLabel(self.groupSimulationOptions)
        self.displayTaiFile.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayTaiFile.sizePolicy().hasHeightForWidth())
        self.displayTaiFile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.displayTaiFile.setFont(font)
        self.displayTaiFile.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayTaiFile.setText(_fromUtf8(""))
        self.displayTaiFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.displayTaiFile.setWordWrap(False)
        self.displayTaiFile.setObjectName(_fromUtf8("displayTaiFile"))
        self.gridLayout_4.addWidget(self.displayTaiFile, 3, 2, 1, 1)
        self.label = QtGui.QLabel(self.groupSimulationOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupSimulationOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupSimulationOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupSimulationOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.groupSimulationOptions, 0, 0, 1, 1)
        self.groupFlushingOptions = QtGui.QGroupBox(self.tabOptions)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupFlushingOptions.sizePolicy().hasHeightForWidth())
        self.groupFlushingOptions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupFlushingOptions.setFont(font)
        self.groupFlushingOptions.setObjectName(_fromUtf8("groupFlushingOptions"))
        self.formLayout = QtGui.QFormLayout(self.groupFlushingOptions)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_editTimeDetect = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editTimeDetect.setFont(font)
        self.lbl_editTimeDetect.setObjectName(_fromUtf8("lbl_editTimeDetect"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_editTimeDetect)
        self.editTimeDetect = QtGui.QDoubleSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editTimeDetect.setFont(font)
        self.editTimeDetect.setDecimals(0)
        self.editTimeDetect.setMaximum(256.0)
        self.editTimeDetect.setObjectName(_fromUtf8("editTimeDetect"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.editTimeDetect)
        self.lbl_editDelayFlush = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editDelayFlush.setFont(font)
        self.lbl_editDelayFlush.setObjectName(_fromUtf8("lbl_editDelayFlush"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_editDelayFlush)
        self.editDelayFlush = QtGui.QDoubleSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editDelayFlush.setFont(font)
        self.editDelayFlush.setDecimals(0)
        self.editDelayFlush.setMaximum(256.0)
        self.editDelayFlush.setObjectName(_fromUtf8("editDelayFlush"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.editDelayFlush)
        self.lbl_editDelayClose = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editDelayClose.setFont(font)
        self.lbl_editDelayClose.setObjectName(_fromUtf8("lbl_editDelayClose"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_editDelayClose)
        self.editDelayClose = QtGui.QDoubleSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editDelayClose.setFont(font)
        self.editDelayClose.setDecimals(0)
        self.editDelayClose.setMaximum(256.0)
        self.editDelayClose.setObjectName(_fromUtf8("editDelayClose"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.editDelayClose)
        self.lbl_editDurationFlush = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editDurationFlush.setFont(font)
        self.lbl_editDurationFlush.setObjectName(_fromUtf8("lbl_editDurationFlush"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl_editDurationFlush)
        self.editDurationFlush = QtGui.QDoubleSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editDurationFlush.setFont(font)
        self.editDurationFlush.setDecimals(0)
        self.editDurationFlush.setMaximum(256.0)
        self.editDurationFlush.setObjectName(_fromUtf8("editDurationFlush"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.editDurationFlush)
        self.lbl_editDurationSim = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editDurationSim.setFont(font)
        self.lbl_editDurationSim.setObjectName(_fromUtf8("lbl_editDurationSim"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl_editDurationSim)
        self.editDurationSim = QtGui.QDoubleSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editDurationSim.setFont(font)
        self.editDurationSim.setDecimals(0)
        self.editDurationSim.setMaximum(256.0)
        self.editDurationSim.setObjectName(_fromUtf8("editDurationSim"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.editDurationSim)
        self.lbl_editFlushingRate = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editFlushingRate.setFont(font)
        self.lbl_editFlushingRate.setObjectName(_fromUtf8("lbl_editFlushingRate"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl_editFlushingRate)
        self.editFlushingRate = QtGui.QDoubleSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editFlushingRate.setFont(font)
        self.editFlushingRate.setDecimals(2)
        self.editFlushingRate.setMaximum(100000.0)
        self.editFlushingRate.setObjectName(_fromUtf8("editFlushingRate"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.editFlushingRate)
        self.lbl_editMaxFlush = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editMaxFlush.setFont(font)
        self.lbl_editMaxFlush.setObjectName(_fromUtf8("lbl_editMaxFlush"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl_editMaxFlush)
        self.editMaxFlush = QtGui.QSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editMaxFlush.setFont(font)
        self.editMaxFlush.setMaximum(1000)
        self.editMaxFlush.setObjectName(_fromUtf8("editMaxFlush"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.editMaxFlush)
        self.lbl_editMaxClose = QtGui.QLabel(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.lbl_editMaxClose.setFont(font)
        self.lbl_editMaxClose.setObjectName(_fromUtf8("lbl_editMaxClose"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl_editMaxClose)
        self.editMaxClose = QtGui.QSpinBox(self.groupFlushingOptions)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(11)
        self.editMaxClose.setFont(font)
        self.editMaxClose.setMaximum(1000)
        self.editMaxClose.setObjectName(_fromUtf8("editMaxClose"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.editMaxClose)
        self.gridLayout.addWidget(self.groupFlushingOptions, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.configTabWidget.addTab(self.tabOptions, _fromUtf8(""))
        self.tabEpanet = QtGui.QWidget()
        self.tabEpanet.setObjectName(_fromUtf8("tabEpanet"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabEpanet)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnLoadNetData = QtGui.QPushButton(self.tabEpanet)
        self.btnLoadNetData.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(False)
        self.btnLoadNetData.setFont(font)
        self.btnLoadNetData.setObjectName(_fromUtf8("btnLoadNetData"))
        self.gridLayout_2.addWidget(self.btnLoadNetData, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupFlushNodes = QtGui.QGroupBox(self.tabEpanet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupFlushNodes.sizePolicy().hasHeightForWidth())
        self.groupFlushNodes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupFlushNodes.setFont(font)
        self.groupFlushNodes.setObjectName(_fromUtf8("groupFlushNodes"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupFlushNodes)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radioNodesAll = QtGui.QRadioButton(self.groupFlushNodes)
        self.radioNodesAll.setChecked(True)
        self.radioNodesAll.setObjectName(_fromUtf8("radioNodesAll"))
        self.verticalLayout_3.addWidget(self.radioNodesAll)
        self.radioNodesNZD = QtGui.QRadioButton(self.groupFlushNodes)
        self.radioNodesNZD.setObjectName(_fromUtf8("radioNodesNZD"))
        self.verticalLayout_3.addWidget(self.radioNodesNZD)
        self.radioNodesList = QtGui.QRadioButton(self.groupFlushNodes)
        self.radioNodesList.setObjectName(_fromUtf8("radioNodesList"))
        self.verticalLayout_3.addWidget(self.radioNodesList)
        self.radioNodesNone = QtGui.QRadioButton(self.groupFlushNodes)
        self.radioNodesNone.setObjectName(_fromUtf8("radioNodesNone"))
        self.verticalLayout_3.addWidget(self.radioNodesNone)
        self.btnUpdateNodes = QtGui.QPushButton(self.groupFlushNodes)
        self.btnUpdateNodes.setEnabled(False)
        self.btnUpdateNodes.setObjectName(_fromUtf8("btnUpdateNodes"))
        self.verticalLayout_3.addWidget(self.btnUpdateNodes)
        self.verticalLayout_5.addWidget(self.groupFlushNodes)
        self.groupPipesClose = QtGui.QGroupBox(self.tabEpanet)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupPipesClose.sizePolicy().hasHeightForWidth())
        self.groupPipesClose.setSizePolicy(sizePolicy)
        self.groupPipesClose.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.groupPipesClose.setFont(font)
        self.groupPipesClose.setObjectName(_fromUtf8("groupPipesClose"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupPipesClose)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radioPipesAll = QtGui.QRadioButton(self.groupPipesClose)
        self.radioPipesAll.setChecked(True)
        self.radioPipesAll.setObjectName(_fromUtf8("radioPipesAll"))
        self.verticalLayout_4.addWidget(self.radioPipesAll)
        self.radioPipesByDiameter = QtGui.QRadioButton(self.groupPipesClose)
        self.radioPipesByDiameter.setChecked(False)
        self.radioPipesByDiameter.setObjectName(_fromUtf8("radioPipesByDiameter"))
        self.verticalLayout_4.addWidget(self.radioPipesByDiameter)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_editMinPipeDiam = QtGui.QLabel(self.groupPipesClose)
        self.lbl_editMinPipeDiam.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_editMinPipeDiam.sizePolicy().hasHeightForWidth())
        self.lbl_editMinPipeDiam.setSizePolicy(sizePolicy)
        self.lbl_editMinPipeDiam.setMinimumSize(QtCore.QSize(0, 10))
        self.lbl_editMinPipeDiam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_editMinPipeDiam.setFont(font)
        self.lbl_editMinPipeDiam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_editMinPipeDiam.setMargin(2)
        self.lbl_editMinPipeDiam.setObjectName(_fromUtf8("lbl_editMinPipeDiam"))
        self.horizontalLayout.addWidget(self.lbl_editMinPipeDiam)
        self.editMinPipeDiam = QtGui.QDoubleSpinBox(self.groupPipesClose)
        self.editMinPipeDiam.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMinPipeDiam.sizePolicy().hasHeightForWidth())
        self.editMinPipeDiam.setSizePolicy(sizePolicy)
        self.editMinPipeDiam.setMinimumSize(QtCore.QSize(0, 25))
        self.editMinPipeDiam.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editMinPipeDiam.setFont(font)
        self.editMinPipeDiam.setMaximum(500.0)
        self.editMinPipeDiam.setObjectName(_fromUtf8("editMinPipeDiam"))
        self.horizontalLayout.addWidget(self.editMinPipeDiam)
        self.lbl_editMaxPipeDiam = QtGui.QLabel(self.groupPipesClose)
        self.lbl_editMaxPipeDiam.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_editMaxPipeDiam.sizePolicy().hasHeightForWidth())
        self.lbl_editMaxPipeDiam.setSizePolicy(sizePolicy)
        self.lbl_editMaxPipeDiam.setMinimumSize(QtCore.QSize(0, 10))
        self.lbl_editMaxPipeDiam.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_editMaxPipeDiam.setFont(font)
        self.lbl_editMaxPipeDiam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_editMaxPipeDiam.setMargin(2)
        self.lbl_editMaxPipeDiam.setObjectName(_fromUtf8("lbl_editMaxPipeDiam"))
        self.horizontalLayout.addWidget(self.lbl_editMaxPipeDiam)
        self.editMaxPipeDiam = QtGui.QDoubleSpinBox(self.groupPipesClose)
        self.editMaxPipeDiam.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editMaxPipeDiam.sizePolicy().hasHeightForWidth())
        self.editMaxPipeDiam.setSizePolicy(sizePolicy)
        self.editMaxPipeDiam.setMinimumSize(QtCore.QSize(0, 25))
        self.editMaxPipeDiam.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.editMaxPipeDiam.setFont(font)
        self.editMaxPipeDiam.setMaximum(500.0)
        self.editMaxPipeDiam.setObjectName(_fromUtf8("editMaxPipeDiam"))
        self.horizontalLayout.addWidget(self.editMaxPipeDiam)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.radioPipesList = QtGui.QRadioButton(self.groupPipesClose)
        self.radioPipesList.setObjectName(_fromUtf8("radioPipesList"))
        self.verticalLayout_4.addWidget(self.radioPipesList)
        self.radioPipesNone = QtGui.QRadioButton(self.groupPipesClose)
        self.radioPipesNone.setObjectName(_fromUtf8("radioPipesNone"))
        self.verticalLayout_4.addWidget(self.radioPipesNone)
        self.btnUpdatePipes = QtGui.QPushButton(self.groupPipesClose)
        self.btnUpdatePipes.setEnabled(False)
        self.btnUpdatePipes.setObjectName(_fromUtf8("btnUpdatePipes"))
        self.verticalLayout_4.addWidget(self.btnUpdatePipes)
        self.verticalLayout_5.addWidget(self.groupPipesClose)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 3, 0, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lbl_editNodeList = QtGui.QLabel(self.tabEpanet)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.lbl_editNodeList.setFont(font)
        self.lbl_editNodeList.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_editNodeList.setObjectName(_fromUtf8("lbl_editNodeList"))
        self.gridLayout_3.addWidget(self.lbl_editNodeList, 0, 0, 1, 1)
        self.lbl_editPipeList = QtGui.QLabel(self.tabEpanet)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.lbl_editPipeList.setFont(font)
        self.lbl_editPipeList.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_editPipeList.setObjectName(_fromUtf8("lbl_editPipeList"))
        self.gridLayout_3.addWidget(self.lbl_editPipeList, 0, 1, 1, 1)
        self.editNodeList = QtGui.QPlainTextEdit(self.tabEpanet)
        self.editNodeList.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.editNodeList.setFont(font)
        self.editNodeList.setObjectName(_fromUtf8("editNodeList"))
        self.gridLayout_3.addWidget(self.editNodeList, 1, 0, 1, 1)
        self.editPipeList = QtGui.QPlainTextEdit(self.tabEpanet)
        self.editPipeList.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.editPipeList.setFont(font)
        self.editPipeList.setObjectName(_fromUtf8("editPipeList"))
        self.gridLayout_3.addWidget(self.editPipeList, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.displayEpanetFile = QtGui.QLabel(self.tabEpanet)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.displayEpanetFile.setFont(font)
        self.displayEpanetFile.setObjectName(_fromUtf8("displayEpanetFile"))
        self.gridLayout_2.addWidget(self.displayEpanetFile, 0, 1, 1, 1)
        self.configTabWidget.addTab(self.tabEpanet, _fromUtf8(""))
        self.tabDakota = QtGui.QWidget()
        self.tabDakota.setObjectName(_fromUtf8("tabDakota"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabDakota)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.textEditDakotaFile = QtGui.QPlainTextEdit(self.tabDakota)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Lucida Console"))
        font.setItalic(False)
        self.textEditDakotaFile.setFont(font)
        self.textEditDakotaFile.setObjectName(_fromUtf8("textEditDakotaFile"))
        self.gridLayout_5.addWidget(self.textEditDakotaFile, 0, 2, 3, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tabDakota)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser_2.sizePolicy().hasHeightForWidth())
        self.textBrowser_2.setSizePolicy(sizePolicy)
        self.textBrowser_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.verticalLayout_6.addWidget(self.textBrowser_2)
        self.checkBoxVerbose = QtGui.QCheckBox(self.tabDakota)
        font = QtGui.QFont()
        font.setItalic(False)
        self.checkBoxVerbose.setFont(font)
        self.checkBoxVerbose.setObjectName(_fromUtf8("checkBoxVerbose"))
        self.verticalLayout_6.addWidget(self.checkBoxVerbose)
        self.btnRestoreDakotaDefaults = QtGui.QPushButton(self.tabDakota)
        font = QtGui.QFont()
        font.setItalic(False)
        self.btnRestoreDakotaDefaults.setFont(font)
        self.btnRestoreDakotaDefaults.setObjectName(_fromUtf8("btnRestoreDakotaDefaults"))
        self.verticalLayout_6.addWidget(self.btnRestoreDakotaDefaults)
        self.gridLayout_5.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.configTabWidget.addTab(self.tabDakota, _fromUtf8(""))
        self.tabResults = QtGui.QWidget()
        self.tabResults.setObjectName(_fromUtf8("tabResults"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabResults)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.plainTextEditResultsFile = QtGui.QPlainTextEdit(self.tabResults)
        font = QtGui.QFont()
        font.setItalic(False)
        self.plainTextEditResultsFile.setFont(font)
        self.plainTextEditResultsFile.setObjectName(_fromUtf8("plainTextEditResultsFile"))
        self.gridLayout_6.addWidget(self.plainTextEditResultsFile, 0, 0, 1, 1)
        self.configTabWidget.addTab(self.tabResults, _fromUtf8(""))
        self.verticalLayout.addWidget(self.configTabWidget)
        self.moduleTabs.addTab(self.flushingTab, _fromUtf8(""))
        self.boosterTab = QtGui.QWidget()
        self.boosterTab.setObjectName(_fromUtf8("boosterTab"))
        self.moduleTabs.addTab(self.boosterTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.moduleTabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuControl = QtGui.QMenu(self.menubar)
        self.menuControl.setObjectName(_fromUtf8("menuControl"))
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_Project = QtGui.QAction(MainWindow)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionRun = QtGui.QAction(MainWindow)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionSet_Defaults = QtGui.QAction(MainWindow)
        self.actionSet_Defaults.setObjectName(_fromUtf8("actionSet_Defaults"))
        self.action_ExitFlushing = QtGui.QAction(MainWindow)
        self.action_ExitFlushing.setObjectName(_fromUtf8("action_ExitFlushing"))
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSet_Defaults)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_ExitFlushing)
        self.menuFile.addSeparator()
        self.menuControl.addAction(self.actionRun)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())

        self.retranslateUi(MainWindow)
        self.moduleTabs.setCurrentIndex(0)
        self.configTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Flushing Response", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "CWaRK 0.1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Contaminated Water Response Toolkit</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Put a cool logo here</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_displayProjectDirectory.setText(QtGui.QApplication.translate("MainWindow", "Project Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayProjectDirectory.setText(QtGui.QApplication.translate("MainWindow", "No project opened yet", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Project Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayProjectName.setText(QtGui.QApplication.translate("MainWindow", "No project name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSimulationOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Simulation Scenario Options", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFindInp.setStatusTip(QtGui.QApplication.translate("MainWindow", "Choose the EPANET .inp file that contains your network data", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFindInp.setText(QtGui.QApplication.translate("MainWindow", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFindTsg.setText(QtGui.QApplication.translate("MainWindow", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(1, QtGui.QApplication.translate("MainWindow", "ec", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(2, QtGui.QApplication.translate("MainWindow", "tec", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(3, QtGui.QApplication.translate("MainWindow", "mc", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(4, QtGui.QApplication.translate("MainWindow", "vc", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(5, QtGui.QApplication.translate("MainWindow", "pd", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(6, QtGui.QApplication.translate("MainWindow", "pe", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseImpactMetric.setItemText(7, QtGui.QApplication.translate("MainWindow", "pk", None, QtGui.QApplication.UnicodeUTF8))
        self.displayImpactMetric.setText(QtGui.QApplication.translate("MainWindow", "No impact measure selected yet", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonFindTai.setText(QtGui.QApplication.translate("MainWindow", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "EPANET Input File (.inp)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Scenario File (.tsg or .tsi)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Impact Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Health Impacts File (.tai)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupFlushingOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Flushing Response Options", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editTimeDetect.setText(QtGui.QApplication.translate("MainWindow", "Time when contamination discovered (hrs):", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editDelayFlush.setText(QtGui.QApplication.translate("MainWindow", "Delay from detection to start of flushing (hrs):", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editDelayClose.setText(QtGui.QApplication.translate("MainWindow", "Delay from detection to closing of pipes/valves (hrs):", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editDurationFlush.setText(QtGui.QApplication.translate("MainWindow", "Duration of flushing (hrs):", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editDurationSim.setText(QtGui.QApplication.translate("MainWindow", "Total simulation duration (hrs):", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editFlushingRate.setText(QtGui.QApplication.translate("MainWindow", "Maximum flushing rate (GPM):", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editMaxFlush.setText(QtGui.QApplication.translate("MainWindow", "Maximum number of flushing nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editMaxClose.setText(QtGui.QApplication.translate("MainWindow", "Maximum number of pipes/valves that can be closed:", None, QtGui.QApplication.UnicodeUTF8))
        self.configTabWidget.setTabText(self.configTabWidget.indexOf(self.tabOptions), QtGui.QApplication.translate("MainWindow", "General Options", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoadNetData.setText(QtGui.QApplication.translate("MainWindow", "Refresh Network", None, QtGui.QApplication.UnicodeUTF8))
        self.groupFlushNodes.setTitle(QtGui.QApplication.translate("MainWindow", "Nodes available for flushing", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNodesAll.setText(QtGui.QApplication.translate("MainWindow", "All nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNodesNZD.setText(QtGui.QApplication.translate("MainWindow", "All non-zero demand nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNodesList.setText(QtGui.QApplication.translate("MainWindow", "Custom list", None, QtGui.QApplication.UnicodeUTF8))
        self.radioNodesNone.setText(QtGui.QApplication.translate("MainWindow", "None (off)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdateNodes.setText(QtGui.QApplication.translate("MainWindow", "Update node list", None, QtGui.QApplication.UnicodeUTF8))
        self.groupPipesClose.setTitle(QtGui.QApplication.translate("MainWindow", "Pipes available to close", None, QtGui.QApplication.UnicodeUTF8))
        self.radioPipesAll.setText(QtGui.QApplication.translate("MainWindow", "All pipes", None, QtGui.QApplication.UnicodeUTF8))
        self.radioPipesByDiameter.setText(QtGui.QApplication.translate("MainWindow", "Pipes within specified diameter", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editMinPipeDiam.setText(QtGui.QApplication.translate("MainWindow", "Min", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editMaxPipeDiam.setText(QtGui.QApplication.translate("MainWindow", "Max", None, QtGui.QApplication.UnicodeUTF8))
        self.radioPipesList.setText(QtGui.QApplication.translate("MainWindow", "Custom list", None, QtGui.QApplication.UnicodeUTF8))
        self.radioPipesNone.setText(QtGui.QApplication.translate("MainWindow", "None (off)", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdatePipes.setText(QtGui.QApplication.translate("MainWindow", "Update pipe list", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editNodeList.setText(QtGui.QApplication.translate("MainWindow", "Selected Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_editPipeList.setText(QtGui.QApplication.translate("MainWindow", "Selected Pipes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayEpanetFile.setText(QtGui.QApplication.translate("MainWindow", "<no network loaded>", None, QtGui.QApplication.UnicodeUTF8))
        self.configTabWidget.setTabText(self.configTabWidget.indexOf(self.tabEpanet), QtGui.QApplication.translate("MainWindow", "Network Details", None, QtGui.QApplication.UnicodeUTF8))
        self.textEditDakotaFile.setPlainText(QtGui.QApplication.translate("MainWindow", "method\n"
" max_iterations = 100\n"
" max_function_evaluations = 2000\n"
" coliny_ea\n"
"  population_size = 50\n"
"  initialization_type\n"
"   unique_random\n"
"  fitness_type\n"
"   linear_rank\n"
"  crossover_rate = 0.8\n"
"  crossover_type\n"
"   uniform\n"
"  mutation_rate = 1\n"
"  mutation_type\n"
"   offset_uniform\n"
"  constraint_penalty = 10\n"
"  seed = 11011011", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser_2.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-weight:600;\">WARNING</span><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">: editing the Daktoa solver method details is an advanced feature. Help with Dakota can be obtained from the Dakota web site: http://dakota.sandia.gov.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">The default values should be acceptable for most users.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Lucida Grande\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt; font-style:italic;\">The following is the default method, to copy back in case of erroneous editing:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Lucida Grande\'; font-size:10pt;\"></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">method</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\"> max_iterations = 100</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\"> max_function_evaluations = 2000</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\"> coliny_ea</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  population_size = 50</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  initialization_type</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">   unique_random</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  fitness_type</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">   linear_rank</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  crossover_rate = 0.8</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  crossover_type</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">   uniform</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  mutation_rate = 1</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  mutation_type</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">   offset_uniform</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  constraint_penalty = 10</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Lucida Grande\'; font-size:10pt;\">  seed = 11011011</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxVerbose.setText(QtGui.QApplication.translate("MainWindow", "Print verbose output to screen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRestoreDakotaDefaults.setText(QtGui.QApplication.translate("MainWindow", "Restore Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.configTabWidget.setTabText(self.configTabWidget.indexOf(self.tabDakota), QtGui.QApplication.translate("MainWindow", "Dakota Details (advanced)", None, QtGui.QApplication.UnicodeUTF8))
        self.configTabWidget.setTabText(self.configTabWidget.indexOf(self.tabResults), QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.moduleTabs.setTabText(self.moduleTabs.indexOf(self.flushingTab), QtGui.QApplication.translate("MainWindow", "Flushing Response Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.moduleTabs.setTabText(self.moduleTabs.indexOf(self.boosterTab), QtGui.QApplication.translate("MainWindow", "Hyperchlorination Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuControl.setTitle(QtGui.QApplication.translate("MainWindow", "Flushing", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Project.setText(QtGui.QApplication.translate("MainWindow", "New Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setText(QtGui.QApplication.translate("MainWindow", "Open Project...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project.setText(QtGui.QApplication.translate("MainWindow", "Save Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRun.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setToolTip(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Defaults.setText(QtGui.QApplication.translate("MainWindow", "Set Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ExitFlushing.setText(QtGui.QApplication.translate("MainWindow", "Exit Flushing", None, QtGui.QApplication.UnicodeUTF8))

